spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lily
    password: Lily+123456
    url: jdbc:mysql://121.40.252.15:3306/user_center_prod?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false