spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LWY-0212lwy
    url: jdbc:mysql://localhost:3306/user_center_prod?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false